name: Release

on:
  push:
    tags:
      - v**

jobs:
  container-main:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: build/Dockerfile
      vendor: "Compliance Operator Authors"
      platforms: "linux/amd64,linux/ppc64le,linux/s390x"

  openscap-container:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: openscap-ocp
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: images/openscap/Dockerfile
      vendor: "Compliance Operator Authors"
      platforms: "linux/amd64,linux/ppc64le,linux/s390x"

  bundle-container:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-bundle
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: bundle.Dockerfile
      vendor: "Compliance Operator Authors"
      platforms: "linux/amd64,linux/ppc64le,linux/s390x"

  catalog-container-push-pr:
    # Temporary workaround for SBOM issue https://github.com/metal-toolbox/container-push/pull/77
    if: always()
    needs:
      - container-main
      - openscap-container
      - bundle-container
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-catalog
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: catalog.Dockerfile
      vendor: "Compliance Operator Authors"
      prepare_command: |
        make catalog-docker BUNDLE_IMGS=ghcr.io/complianceascode/compliance-operator-bundle:${GITHUB_REF_NAME}
      platforms: "linux/amd64,linux/ppc64le,linux/s390x"
