name: Release latest

on:
  push:
    branches: [ 'master' ]

jobs:
  # Push to latest
  operator-container-push-latest:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/ppc64le
          - linux/s390x
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator
      registry_org: complianceascode
      tag: latest
      dockerfile_path: build/Dockerfile
      vendor: 'Compliance Operator Authors'
      platforms: ${{ matrix.platform }}

  bundle-container-push-latest:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/ppc64le
          - linux/s390x
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-bundle
      registry_org: complianceascode
      tag: latest
      dockerfile_path: bundle.Dockerfile
      vendor: 'Compliance Operator Authors'
      platforms: ${{ matrix.platform }}

  openscap-container-push-latest:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/ppc64le
          - linux/s390x
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: openscap-ocp
      registry_org: complianceascode
      tag: latest
      dockerfile_path: images/openscap/Dockerfile
      vendor: 'Compliance Operator Authors'
      platforms: ${{ matrix.platform }}

  catalog-container-push-pr:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/ppc64le
          - linux/s390x
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-catalog
      registry_org: complianceascode
      tag: latest
      dockerfile_path: catalog.Dockerfile
      vendor: 'Compliance Operator Authors'
      prepare_command: |
        make catalog-docker BUNDLE_IMGS=ghcr.io/complianceascode/compliance-operator-bundle:latest
      platforms: ${{ matrix.platform }}
