name: Release

on:
  push:
    tags:
      - v**

jobs:
  container-main:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: build/Dockerfile
      vendor: 'Compliance Operator Authors'

  bundle-container:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-bundle
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: bundle.Dockerfile
      vendor: 'Compliance Operator Authors'

  catalog-container:
    runs-on: ubuntu-latest
    needs: bundle-container
    if: always() # remove this after we fix signing

    permissions:
      packages: write
      contents: read

    outputs:
      image-digest: ${{ steps.container_info.outputs.image-digest }}
      image-tags: ${{ steps.container_info.outputs.image-tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0

      - name: Login to ghcr.io
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/complianceascode/compliance-operator-catalog
          tags: |
            type=raw,value=${GITHUB_REF_NAME}
            type=sha,format=long
            type=raw,value=${GITHUB_REF_NAME},enable=true
          labels: |
            org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
            org.opencontainers.image.title=compliance-operator-catalog
            org.opencontainers.image.version=${GITHUB_REF_NAME}
            org.opencontainers.image.licenses='Apache-2.0'
            org.opencontainers.image.vendor='Compliance Operator Authors'
        
      - name: Generate catalog dockerfile
        id: generate_catalog_dockerfile
        run: |
          make catalog-docker BUNDLE_IMGS=ghcr.io/complianceascode/compliance-operator-bundle:${GITHUB_REF_NAME}

      - name: Build container images and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: catalog.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          platforms: 'linux/amd64'

      - name: Get container info
        id: container_info
        run: |
          image_tags="${GITHUB_REF_NAME},sha-$(git rev-parse HEAD)"
          echo "::set-output name=image-digest::${{ steps.docker_build.outputs.digest }}"
          echo "::set-output name=image-tags::${image_tags}"