name: Release

on:
  push:
    tags:
      - v**

jobs:
  container-main:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/ppc64le
          - linux/s390x
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: build/Dockerfile
      vendor: 'Compliance Operator Authors'
      platforms: ${{ matrix.platform }}

  bundle-container:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/ppc64le
          - linux/s390x
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-bundle
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: bundle.Dockerfile
      vendor: 'Compliance Operator Authors'
      platforms: ${{ matrix.platform }}

  catalog-container-push-pr:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/ppc64le
          - linux/s390x
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-catalog
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: catalog.Dockerfile
      vendor: 'Compliance Operator Authors'
      prepare_command: |
        make catalog-docker BUNDLE_IMGS=ghcr.io/complianceascode/compliance-operator-bundle:${GITHUB_REF_NAME}
      platforms: ${{ matrix.platform }}
